version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - default
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      POSTGRES_HOST: database
    depends_on:
      - database
    ports:
      - 8080:8080
    expose:
      - 8080
volumes:
  data:
